name: livedemo

services:
  backend:
    build:
      context: ..
      dockerfile: livedemo/docker/backend.Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: livedemo/docker/frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
