name: livedemo

services:
  backend:
    build:
      context: ..
      dockerfile: livedemo/docker/backend.Dockerfile
    environment:
      LIVEDEMO_DB_URL: sqlite:////var/livedemo/db.sqlite
    volumes:
      - livedemo-data:/var/livedemo
    ports:
      - "${BACKEND_PORT:-8000}:8000"

  frontend:
    build:
      context: ..
      dockerfile: livedemo/docker/frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8080}:80"

volumes:
  livedemo-data:
